Making some small clarification changes to the Okta doc section
redhat-cop/group-sync-operator pull request #104
Opened 2021-07-20 19:07 UTC by michaelryanmcneill

Two small tweaks to ensure that people are aware of what values to enter in the custom resource, primarily focused on clarifying what the `appId` is.

2021-07-23 23:47 UTC, sabre1041 requested changes
Quick change

2021-07-23 23:47 UTC, sabre1041 commented on README.md
> +        appId: 0oad5lTSBOMUBOBVVQSC
@michaelryanmcneill Can this be made generic just to confirm that it is not a real application ID?

2021-08-06 04:59 UTC, sabre1041 commented
@michaelryanmcneill Any chance you would be able to take a look at the requested changes?

2021-08-06 16:30 UTC, jrchamp commented on README.md
> +| `url` | Okta URL which can be found under the "Okta Domain" in your application settings (must contain the protocol and a trailing slash) | `''`  | Yes |
Optional, but it looks like for URLs this component is called "scheme" instead: https://en.wikipedia.org/wiki/URL#Syntax
```suggestion
| `url` | Okta URL which can be found under the "Okta Domain" in your application settings (must contain the scheme and a trailing slash) | `''`  | Yes |
```

2022-03-10 01:18 UTC, michaelryanmcneill commented
Sorry, for some reason I didn't see notifications for this one. Fixing and will push changes.

2022-03-10 01:23 UTC, michaelryanmcneill commented
This should be taken care of now @sabre1041 and ready to merge. Sorry again for the delay!

2022-03-10 06:33 UTC, sabre1041 approved these changes
LGTM

2022-03-10 06:33 UTC, merged

2022-03-10 06:33 UTC, sabre1041 commented
Thanks @michaelryanmcneill for following through on the changes