Add support for more than 20 Okta groups
redhat-cop/group-sync-operator pull request #106
Opened 2021-07-22 18:55 UTC by klofton-bw

There was an issue with the Okta syncer due to the way the API call was made and how the client returned the groups in pages. This fix makes the number of groups the syncer can pull customizable with a default of 1000.

2021-07-22 19:37 UTC, Jmainguy commented
Code looks good to my eyeballs, @klofton-bw promises me that the new addition the CRD is optional, and if not set, the default is 1000 groups. Nice work

2021-07-22 19:37 UTC, Jmainguy approved these changes

2021-07-23 03:16 UTC, slmingol approved these changes

2021-08-11 13:34 UTC, klofton-bw commented on README.md
> +### Keycloak
Yeah, removed commit where I moved it

2021-08-11 22:25 UTC, slmingol approved these changes

2021-08-12 00:46 UTC, sabre1041 requested changes
One final change

2021-08-12 00:46 UTC, sabre1041 commented on api/v1alpha1/groupsync_types.go
> +	// +operator-sdk:csv:customresourcedefinitions:type=spec,displayName="Group Limit",xDescriptors={"urn:alm:descriptor:com.tectonic.ui:text"}
Since this is an integer, can we use `urn:alm:descriptor:com.tectonic.ui:number` since it is an integer?

2021-08-12 22:48 UTC, slmingol approved these changes

2021-08-13 12:42 UTC, sabre1041 approved these changes
LGTM

2021-08-13 13:06 UTC, merged