initial commit
redhat-cop/group-sync-operator pull request #125
Opened 2021-09-08 21:23 UTC by davidkarlsen

Fixes #111.
Currently a draft as docs are needed to add, and also there is a snag with app-based auth when using the v4 client.

2021-09-12 20:16 UTC, davidkarlsen commented
@sabre1041 PTAL.

This makes it possible to map teams from github, resolving the userId to the IDP-identity. This way the github-teams member uids will align with the id used in the IDP when using AAD as IDP. Use-case outlined in #111.

Note that this introduces a couple of fields in the CRD when using GH as provider.

2021-09-19 12:13 UTC, davidkarlsen commented
@sabre1041 PTAL?

2021-09-19 15:23 UTC, sabre1041 requested changes
Small docs change.

I do not have a SCIM endpoint, so my testing later today will be limited to ensuring that the existing GitHub functionality is retained

2021-09-19 15:23 UTC, sabre1041 commented on README.md
> +* Under "permissions and events" the app will need read-only access to the "Members" permission in the "Organization" section. NOTE: If you enable `MapByScimId` this permissions needs to be _Read & W
```suggestion
* Under "permissions and events", the app will need read-only access to the "Members" permission in the "Organization" section. NOTE: If you enable `mapByScimId`, this permissions needs to be _Read & Write_, though the operator only does read-only operations. The reason for this is the use of the v4 graphql api-endpoint.
```

2021-09-20 05:06 UTC, sabre1041 approved these changes
LGTM

2021-09-20 05:07 UTC, merged

2021-09-20 18:07 UTC, davidkarlsen commented
> LGTM

Awesome - when (ca) will the next release be?