update the scope of the OAuthTocken for GitHub
redhat-cop/group-sync-operator pull request #276
Opened 2023-07-11 15:17 UTC by rbaumgar

2023-07-23 12:33 UTC, sabre1041 requested changes
Minor formatting change.

2023-07-23 12:33 UTC, sabre1041 commented on README.md
> +The OAuth Personal Access Token needs to scope of admin:org/read:org.
```suggestion
The OAuth Personal Access Token needs to scope of `admin:org/read:org`.
```

2023-07-24 05:21 UTC, rbaumgar commented on README.md
> +The OAuth Personal Access Token needs to scope of admin:org/read:org.
thx!

2023-12-24 21:28 UTC, sabre1041 commented
@rbaumgar any chance you might be able to address the requested changes?

2024-01-02 10:27 UTC, rbaumgar commented
done. please review

2024-04-12 20:48 UTC, sabre1041 approved these changes
LGTM

2024-04-12 20:48 UTC, merged

2024-04-15 07:36 UTC, rbaumgar commented
thx